version: "3"

services:
  web:
    build: .
    container_name: web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8002:80"
    depends_on:
      - database
  database:
    image: mysql:5.7
    container_name: mydatabase
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
